services:

  app:
    build: ./
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/
    links:
      - database
  
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: blog
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
